version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource # Replace with your desired plugin ID
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=myadminpasswd
      - GF_SERVER_ROOT_URL=http://18.217.148.82:3000
    restart: unless-stopped

volumes:
  grafana-data: