version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-provisioning/dashboards/default.yml:/etc/grafana/provisioning/dashboards/default.yml
      - ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource # Replace with your desired plugin ID
      - GF_SERVER_ROOT_URL=http://18.218.224.50:3000
    restart: unless-stopped
